# Generated by Django 4.2.7 on 2023-12-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_title_post_generated_name_savedname'),
    ]

    operations = [

        migrations.AlterField(
            model_name='savedname',
            name='saved_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
