# Generated by Django 4.2.7 on 2023-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_title_post_generated_name_and_more'),
    ]

    operations = [
        
    ]
